export const manifests: Array<UmbExtensionManifest> = [
  {
    type: 'headerApp',
    alias: 'DynamicDave.EnvironmentIndicator.HeaderApp',
    name: 'Environment Indicator Header App',
    element: () => import('./environment-badge.element.js'),
    weight: 1000,
  },
  {
    type: 'localization',
    alias: 'DynamicDave.EnvironmentIndicator.Localization.En',
    name: 'Environment Indicator English',
    weight: -100,
    meta: { culture: 'en' },
    js: () => import('./localization/en.js'),
  },
  {
    type: 'localization',
    alias: 'DynamicDave.EnvironmentIndicator.Localization.Nl',
    name: 'Environment Indicator Dutch',
    weight: -100,
    meta: { culture: 'nl' },
    js: () => import('./localization/nl.js'),
  },
  {
    type: 'localization',
    alias: 'DynamicDave.EnvironmentIndicator.Localization.De',
    name: 'Environment Indicator German',
    weight: -100,
    meta: { culture: 'de' },
    js: () => import('./localization/de.js'),
  },
  {
    type: 'localization',
    alias: 'DynamicDave.EnvironmentIndicator.Localization.Fr',
    name: 'Environment Indicator French',
    weight: -100,
    meta: { culture: 'fr' },
    js: () => import('./localization/fr.js'),
  },
  {
    type: 'localization',
    alias: 'DynamicDave.EnvironmentIndicator.Localization.Da',
    name: 'Environment Indicator Danish',
    weight: -100,
    meta: { culture: 'da' },
    js: () => import('./localization/da.js'),
  },
];
