// This file is auto-generated by @hey-api/openapi-ts

export { EnvironmentInfoService, type Options } from './sdk.gen';
export type { ClientOptions, EnvironmentInfoModel, GetEnvironmentInfoData, GetEnvironmentInfoErrors, GetEnvironmentInfoResponse, GetEnvironmentInfoResponses } from './types.gen';
