// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:44412' | (string & {});
};

export type EnvironmentInfoModel = {
    environmentName: string;
    label: string;
    color: string;
    host?: string | null;
    umbracoVersion: string;
};

export type GetEnvironmentInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/dynamicdave-environment/api/v1/info';
};

export type GetEnvironmentInfoErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetEnvironmentInfoResponses = {
    /**
     * OK
     */
    200: EnvironmentInfoModel;
};

export type GetEnvironmentInfoResponse = GetEnvironmentInfoResponses[keyof GetEnvironmentInfoResponses];
